# Generated by Django 5.2.15 on 2026-06-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('transport', '运输费'), ('labor', '人工费'), ('venue', '场地费'), ('maintenance', '维保费'), ('temporary_purchase', '临时采购费'), ('abnormal_handling', '异常处理费')], max_length=30, verbose_name='费用类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='费用说明')),
                ('expense_date', models.DateField(verbose_name='费用发生日期')),
                ('operator', models.CharField(blank=True, max_length=100, null=True, verbose_name='经办人')),
                ('receipt_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='票据编号')),
                ('is_abnormal_cost', models.BooleanField(default=False, verbose_name='是否为异常费用')),
                ('abnormal_remark', models.TextField(blank=True, null=True, verbose_name='异常费用说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tour_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='tours.tourtask', verbose_name='巡演任务')),
            ],
            options={
                'verbose_name': '巡演成本项',
                'verbose_name_plural': '巡演成本项',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='TourSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_no', models.CharField(max_length=50, unique=True, verbose_name='结算单号')),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='运输费合计')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='人工费合计')),
                ('venue_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='场地费合计')),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='维保费合计')),
                ('temporary_purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='临时采购费合计')),
                ('abnormal_handling_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='异常处理费合计')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总成本')),
                ('abnormal_cost_note', models.TextField(blank=True, null=True, verbose_name='异常费用说明')),
                ('settlement_status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('confirmed', '已确认')], default='draft', max_length=20, verbose_name='结算状态')),
                ('settler', models.CharField(blank=True, max_length=100, null=True, verbose_name='结算人')),
                ('settlement_date', models.DateField(blank=True, null=True, verbose_name='结算日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tour_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='tours.tourtask', verbose_name='巡演任务')),
            ],
            options={
                'verbose_name': '巡演结算单',
                'verbose_name_plural': '巡演结算单',
                'ordering': ['-created_at'],
            },
        ),
    ]
