# Generated by Django 5.2.15 on 2026-06-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("props", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_date", models.DateField(verbose_name="损耗日期")),
                ("damage_quantity", models.IntegerField(verbose_name="损耗数量")),
                (
                    "damage_reason",
                    models.CharField(max_length=500, verbose_name="损耗原因"),
                ),
                ("handler", models.CharField(max_length=100, verbose_name="处理人")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="damage_records",
                        to="props.prop",
                        verbose_name="道具",
                    ),
                ),
            ],
            options={
                "verbose_name": "损耗记录",
                "verbose_name_plural": "损耗记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoadingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loading_date", models.DateField(verbose_name="装车日期")),
                (
                    "loading_quantity",
                    models.IntegerField(default=1, verbose_name="装车数量"),
                ),
                ("operator", models.CharField(max_length=100, verbose_name="操作人")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loading_records",
                        to="props.prop",
                        verbose_name="道具",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loading_records",
                        to="vehicles.vehicle",
                        verbose_name="车辆",
                    ),
                ),
            ],
            options={
                "verbose_name": "装车登记",
                "verbose_name_plural": "装车登记",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnloadingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unloading_date", models.DateField(verbose_name="卸车日期")),
                ("unloading_quantity", models.IntegerField(verbose_name="卸车数量")),
                ("operator", models.CharField(max_length=100, verbose_name="操作人")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "loading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unloading_record",
                        to="loading.loadingrecord",
                        verbose_name="装车记录",
                    ),
                ),
                (
                    "prop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unloading_records",
                        to="props.prop",
                        verbose_name="道具",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unloading_records",
                        to="vehicles.vehicle",
                        verbose_name="车辆",
                    ),
                ),
            ],
            options={
                "verbose_name": "卸车归库",
                "verbose_name_plural": "卸车归库",
                "ordering": ["-created_at"],
            },
        ),
    ]
