# Generated by Django 5.2.15 on 2026-06-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="道具编号"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="道具名称")),
                (
                    "material",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="材质"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_store", "在库"),
                            ("loaded", "已装车"),
                            ("damaged", "损坏"),
                            ("lost", "丢失"),
                        ],
                        default="in_store",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="存放位置"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="props",
                        to="programs.program",
                        verbose_name="所属剧目",
                    ),
                ),
            ],
            options={
                "verbose_name": "道具",
                "verbose_name_plural": "道具",
                "ordering": ["-created_at"],
            },
        ),
    ]
