# Generated by Django 5.2.15 on 2026-06-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('props', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='最近维保时间'),
        ),
        migrations.AddField(
            model_name='prop',
            name='maintenance_cycle_days',
            field=models.IntegerField(default=90, verbose_name='维保周期(天)'),
        ),
        migrations.AddField(
            model_name='prop',
            name='maintenance_status',
            field=models.CharField(choices=[('normal', '正常'), ('pending', '待维保'), ('overdue', '超期未维保'), ('in_maintenance', '维保中')], default='normal', max_length=20, verbose_name='维保状态'),
        ),
        migrations.AddField(
            model_name='prop',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True, verbose_name='下次维保时间'),
        ),
        migrations.AddField(
            model_name='prop',
            name='scrap_status',
            field=models.CharField(choices=[('active', '在用'), ('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('scrapped', '已报废')], default='active', max_length=20, verbose_name='报废状态'),
        ),
        migrations.AlterField(
            model_name='prop',
            name='status',
            field=models.CharField(choices=[('in_store', '在库'), ('loaded', '已装车'), ('damaged', '损坏'), ('lost', '丢失'), ('scrapped', '已报废')], default='in_store', max_length=20, verbose_name='当前状态'),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('repair', '维修'), ('maintenance', '保养'), ('inspection', '复检')], max_length=20, verbose_name='维保类型')),
                ('maintenance_date', models.DateField(verbose_name='维保日期')),
                ('description', models.TextField(verbose_name='维保描述')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('pending', '待确认')], default='pending', max_length=20, verbose_name='维保结果')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='props.prop', verbose_name='道具')),
            ],
            options={
                'verbose_name': '维保记录',
                'verbose_name_plural': '维保记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('apply_date', models.DateField(verbose_name='申请日期')),
                ('reason', models.TextField(verbose_name='报废原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已驳回'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='审批状态')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人')),
                ('approve_date', models.DateField(blank=True, null=True, verbose_name='审批日期')),
                ('approve_remark', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_applications', to='props.prop', verbose_name='道具')),
            ],
            options={
                'verbose_name': '报废申请',
                'verbose_name_plural': '报废申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
