# Generated by Django 5.2.15 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="车辆编号"
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="车型")),
                ("capacity", models.IntegerField(verbose_name="承载容量")),
                (
                    "current_load",
                    models.IntegerField(default=0, verbose_name="当前装载量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "启用"), ("inactive", "停用")],
                        default="active",
                        max_length=10,
                        verbose_name="车辆状态",
                    ),
                ),
                (
                    "driver",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="责任司机"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "车辆",
                "verbose_name_plural": "车辆",
            },
        ),
    ]
